### ISSUE TITLE
Error: CouchDB disconnected gracefully

### ISSUE THREAD

**Issue by jmatsushita** [jcrugzz/changes-stream#17]
I get the following errors after leaving a connection open for a few hours.

```
[tracker - 27229]: { Error: CouchDB disconnected gracefully
[tracker - 27229]:     at ChangesStream._onEnd (./node_modules/changes-stream/index.js:297:13)
[tracker - 27229]:     at emitNone (events.js:91:20)
[tracker - 27229]:     at IncomingMessage.emit (events.js:185:7)
[tracker - 27229]:     at endReadableNT (_stream_readable.js:974:12)
[tracker - 27229]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[tracker - 27229]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

It then seems that the stream maybe isn't really closed but it would be nice to either mention this in the error message (alongside with some info about the stream which would also be solved with #16).

**Comment by Ti-webdev** [comment]
node v8.1.2
```
Fri, 30 Jun 2017 12:58:50 GMT changes-stream data event fired from the underlying _changes response
Fri, 30 Jun 2017 12:59:20 GMT changes-stream data event fired from the underlying _changes response
....
Fri, 30 Jun 2017 13:57:50 GMT changes-stream data event fired from the underlying _changes response
Fri, 30 Jun 2017 13:58:20 GMT changes-stream request timed out or is inactive, lets retry
Fri, 30 Jun 2017 13:58:20 GMT changes-stream retry request
Fri, 30 Jun 2017 13:58:20 GMT changes-stream cleanup: flushing any possible buffer and killing underlying request
Fri, 30 Jun 2017 13:58:20 GMT changes-stream precleanup: do we have remaining data?
Fri, 30 Jun 2017 13:58:20 GMT changes-stream retry # 1
Fri, 30 Jun 2017 13:58:20 GMT changes-stream retry request
Fri, 30 Jun 2017 13:58:20 GMT changes-stream cleanup: flushing any possible buffer and killing underlying request
Fri, 30 Jun 2017 13:58:20 GMT changes-stream precleanup: do we have remaining data?
Fri, 30 Jun 2017 13:58:21 GMT changes-stream retry # 2
Fri, 30 Jun 2017 13:58:21 GMT changes-stream retry request
Fri, 30 Jun 2017 13:58:21 GMT changes-stream cleanup: flushing any possible buffer and killing underlying request
Fri, 30 Jun 2017 13:58:21 GMT changes-stream precleanup: do we have remaining data?
Fri, 30 Jun 2017 13:58:22 GMT changes-stream retry # 3
Fri, 30 Jun 2017 13:58:22 GMT changes-stream retry request
Fri, 30 Jun 2017 13:58:22 GMT changes-stream cleanup: flushing any possible buffer and killing underlying request
Fri, 30 Jun 2017 13:58:22 GMT changes-stream precleanup: do we have remaining data?
Fri, 30 Jun 2017 13:58:25 GMT changes-stream retry # 4
Fri, 30 Jun 2017 13:58:25 GMT changes-stream retry request
Fri, 30 Jun 2017 13:58:25 GMT changes-stream cleanup: flushing any possible buffer and killing underlying request
Fri, 30 Jun 2017 13:58:25 GMT changes-stream precleanup: do we have remaining data?
Fri, 30 Jun 2017 13:58:29 GMT changes-stream retry # 5
Fri, 30 Jun 2017 13:58:29 GMT changes-stream retry request
Fri, 30 Jun 2017 13:58:29 GMT changes-stream cleanup: flushing any possible buffer and killing underlying request
Fri, 30 Jun 2017 13:58:29 GMT changes-stream precleanup: do we have remaining data?
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: CouchDB disconnected gracefully
    at ChangesStream._onEnd (/usr/src/app/node_modules/changes-stream/index.js:297:13)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
npm info lifecycle cxd-cc@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by Ti-webdev** [comment]
https://github.com/jcrugzz/changes-stream/pull/18
